const level1 = new Level(
    [
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(120, 120, 330),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Chicken(180, 180, 270),
        new Endboss(),
    ],
    [
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),

    ],
    [
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud()
    ],
    [
        new BackgroundObject('img/5_background/layers/air.png', -719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),

        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),

        new BackgroundObject('img/5_background/layers/air.png', 719*2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*2),
        new BackgroundObject('img/5_background/layers/air.png', 719*3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*3),

        new BackgroundObject('img/5_background/layers/air.png', 719*4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*4),
        new BackgroundObject('img/5_background/layers/air.png', 719*5),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*5),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*5),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*5),

        new BackgroundObject('img/5_background/layers/air.png', 719*6),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*6),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*6),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*6),
        new BackgroundObject('img/5_background/layers/air.png', 719*7),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*7),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*7),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*7),

        new BackgroundObject('img/5_background/layers/air.png', 719*8),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*8),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*8),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*8),
        new BackgroundObject('img/5_background/layers/air.png', 719*9),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*9),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*9),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*9),

        new BackgroundObject('img/5_background/layers/air.png', 719*10),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*10),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*10),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*10),
        new BackgroundObject('img/5_background/layers/air.png', 719*11),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*11),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*11),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*11),

        new BackgroundObject('img/5_background/layers/air.png', 719*12),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*12),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*12),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*12),
        new BackgroundObject('img/5_background/layers/air.png', 719*13),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*13),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*13),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*13),

        new BackgroundObject('img/5_background/layers/air.png', 719*14),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*14),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*14),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*14),
        new BackgroundObject('img/5_background/layers/air.png', 719*15),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*15),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*15),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*15),
        new BackgroundObject('img/5_background/layers/air.png', 719*16),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*16),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*16),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*16),
        new BackgroundObject('img/5_background/layers/air.png', 719*17),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*17),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*17),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*17),
        new BackgroundObject('img/5_background/layers/air.png', 719*18),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*18),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*18),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*18),
        new BackgroundObject('img/5_background/layers/air.png', 719*19),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*19),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*19),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*19),
        new BackgroundObject('img/5_background/layers/air.png', 719*20),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*20),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*20),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*20),
        new BackgroundObject('img/5_background/layers/air.png', 719*21),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*21),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*21),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*21),
        new BackgroundObject('img/5_background/layers/air.png', 719*22),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*22),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*22),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*22),
        new BackgroundObject('img/5_background/layers/air.png', 719*23),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*23),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*23),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*23),
        new BackgroundObject('img/5_background/layers/air.png', 719*24),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719*24),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719*24),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719*24),
        new BackgroundObject('img/5_background/layers/air.png', 719*25),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719*25),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719*25),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719*25),
    ]
);